spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/ppmtool"
    username: "ppmtooladmin"
    password: "yourpassword"
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
